config/routes.rb
Rails.application.routes.draw do
  resources :project_cards do
    get :set_theme
    get :reset_theme
    post :upload_theme
    post :upload_image
    post :update_image
  end

  root 'project_cards#index'

end

app/models/project_card.rb
class ProjectCard < ActiveRecord::Base

  THEME = ['theme_1.jpeg', 'theme_2.jpeg', 'theme_3.jpeg', 'theme_4.jpeg', 'theme_5.jpeg', 'theme_6.jpeg', 'theme_7.jpeg', 'theme_8.jpeg', 'theme_9.jpeg', 'theme_10.jpeg', 'theme_11.jpeg', 'theme_12.jpeg']

  attr_accessor :helper_image1, :helper_image2, :helper_image3
  mount_uploader :image1, ProjectCardUploader
  mount_uploader :image2, ProjectCardUploader
  mount_uploader :image3, ProjectCardUploader
  mount_uploader :background_image, ProjectCardUploader
  mount_base64_uploader :image1, ProjectCardUploader, file_name: -> { "file_#{DateTime.now.to_i}" }
  mount_base64_uploader :image2, ProjectCardUploader, file_name: -> { "file_#{DateTime.now.to_i}" }
  mount_base64_uploader :image3, ProjectCardUploader, file_name: -> { "file_#{DateTime.now.to_i}" }
  serialize :property, JSON

  # after_create :create_default_template


  def create_default_template
    self.update_attributes(content: ApplicationController.helpers.project_card_template(self))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/project_cards_controller.rb
class ProjectCardsController < ApplicationController
  before_action :set_project_card, only: [:show, :edit, :update, :destroy]

  # GET /project_cards
  # GET /project_cards.json
  def index
    @project_cards = ProjectCard.all
  end

  # GET /project_cards/1
  # GET /project_cards/1.json
  def show
  end

  # GET /project_cards/new
  def new
    @project_card = ProjectCard.new
  end

  # GET /project_cards/1/edit
  def edit

  end

  # POST /project_cards
  # POST /project_cards.json
  def create
    @project_card = ProjectCard.new(project_card_params)

    respond_to do |format|
      if @project_card.save
        @project_card.create_default_template
        format.html { redirect_to @project_card, notice: 'Project card was successfully created.' }
        format.json { render :show, status: :created, location: @project_card }
      else
        format.html { render :new }
        format.json { render json: @project_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_cards/1
  # PATCH/PUT /project_cards/1.json
  def update
    respond_to do |format|
      if @project_card.update(project_card_params)
        format.js {}
        format.html { redirect_to @project_card, notice: 'Project card was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_card }
      else
        format.html { render :edit }
        format.json { render json: @project_card.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_theme
    @card = ProjectCard.find_by_id(params[:project_card_id])
    @card.background_image = File.open(File.join(Rails.root, "/app/assets/images/#{params[:theme]}"))
    @card.save
  end

  def upload_theme
    @card = ProjectCard.find_by_id(params[:project_card_id])
    @card.update_attributes(background_image: params[:background_image])
  end

  def update_image
    card = ProjectCard.find_by_id(params[:project_card_id])
    status = card.update_attribute(params[:field], params[:value])
    p status;
    respond_to do |format|
      format.json { render json: {image: card.send(params[:field]).url} }
    end
  end

  def upload_image
    card = ProjectCard.find_by_id(params[:project_card_id])
    status = card.update_attribute(params[:field_name], params[:image])
    respond_to do |format|
      format.json { render json: {image: card.send(params[:field_name]).url} }
    end
  end

  def reset_theme
    @card = ProjectCard.find_by_id(params[:project_card_id])
    @card.background_image.remove!
    @card.remove_background_image = true
    @card.background_image = ''
    @card.save
    @card.reload
  end

  # DELETE /project_cards/1
  # DELETE /project_cards/1.json
  def destroy
    @project_card.destroy
    respond_to do |format|
      format.html { redirect_to project_cards_url, notice: 'Project card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project_card
    @project_card = ProjectCard.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_card_params
    params.require(:project_card).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_style(property, field)
    return unless property.present?
    property_hash = JSON.parse(property)
    field_property = property_hash[field]
    if field_property.present?
      "top: #{field_property['top']}px; left: #{field_property['left']}px; position: absolute !important;"
    end
  end

  def set_image_style(property, field)
    return unless property.present?
    property_hash = JSON.parse(property)
    field_property = property_hash[field]
    if field_property.present?
      "border-radius: #{field_property['borderRadius']}px; opacity: #{field_property['opacity']}"
    end
  end

  def set_background(card)
    if card.background_image_url.present?
      "background: url('#{card.background_image_url}') no-repeat; background-size: cover;"
    else
      "background: #2c2c2c"
    end
  end

  def project_card_template(card)
    "<div id='project-card' class='project-card-frame ui-selectable' data-adaptive-background data-ab-css-background>
    <div class='pin-tier'>
      <div class='pin-grip'>
        <img src='/assets/jcpin-e9b7fe4f4035729da16d92c6318c314f8c17917b657cb6c969908e7ac7cd8a44.png' alt='Jcpin'>
      </div>
    </div>

    <div class='name-wrapper draggable-item editable-container resizable-container selectable-item' style='top: 31px; left: 17px; width: 279px; height: 43px; position: absolute !important;'>
      #{card.name}
    </div>

    <div class='location-wrapper draggable-item resizable-container editable-container selectable-item' style='top: 31px; left: 553px; width: 137px; height: 27px; position: absolute !important;'>
      #{card.location}
    </div>

    <div class='price-wrapper draggable-item resizable-container editable-container selectable-item' style='top: 77px; left: 23px; position: absolute !important;'>
       #{card.price}
    </div>

    <div class='resizable-container selectable-item editable-image' style='top: 96px; left: 467px; width: 223px; height: 155px; position: absolute !important;'>
      <img class='image-preview' id='image1' src='#{card.image1_url}' alt='10497334 907125592647296 875846361286219637 o'>
      <div class='soft-edge'></div>
    </div>

    <div class='resizable-container selectable-item editable-image' style='top: 94px; left: 247px; position: absolute !important; height: 158px;'>
      <img class='image-preview' id='image2' src='#{card.image2_url}' alt='File 1485179115'>
      <div class='soft-edge'></div>
    </div>

    <div class='resizable-container selectable-item editable-image' style='top: 260px; left: 10px; width: 228px; height: 150px; position: absolute !important;'>
      <img class='image-preview' id='image3' data-target-border='border_image3' src='#{card.image3_url}' alt='Products'>
      <div class='soft-edge'></div>
    </div>

    <div class='description-wrapper resizable-container draggable-item editable-container selectable-item ui-selectee ui-draggable ui-draggable-handle ui-resizable' data-container='description' style='top: 268.062px; left: 256px; height: 103px; position: absolute !important;' contenteditable='true'>
      #{card.description}
    </div>

    <div class='pull-right' style='position: absolute; right: 15px; bottom: 15px;'>
      <img style='width: 126px; height: 35px;' src='/assets/logo-95a6241bd2a9a75ad70f5bd39f7090517e9bd828083665f5109e1288649cba9a.png' alt='Logo'>
    </div>
  </div>"
  end

end

app/helpers/project_card_helper.rb
module ProjectCardHelper
end

app/helpers/project_cards_helper.rb
module ProjectCardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LiveEditor</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
  <link href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet"/>
  <!--<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>-->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/project_cards/_form.html.erb
<%= form_for(@project_card) do |f| %>
    <% if @project_card.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project_card.errors.count, "error") %> prohibited this project_card from being saved:</h2>

          <ul>
            <% @project_card.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div>
      <%= f.text_field :name, placeholder: 'Project Name' %>
    </div>

    <div>
      <%= f.text_field :location, placeholder: 'Project Location' %>
    </div>

    <div>
      <%= f.text_field :price, placeholder: 'Project price' %>
    </div>

    <div>
      <%= f.text_field :description, placeholder: 'Project description' %>
    </div>

    <div>
      <%= f.file_field :image1, placeholder: 'Project Image1' %>
    </div>

    <div>
      <%= f.file_field :image2, placeholder: 'Project Image2' %>
    </div>

    <div>
      <%= f.file_field :image3, placeholder: 'Project Image3' %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/project_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Project Cards</h1>

<table class="table table-bordered">
  <thead>
  <tr>
    <th> Name</th>
    <th> Description</th>
    <th> Location</th>
    <th> Price</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @project_cards.each do |project_card| %>
      <tr>
        <td> <%= project_card.name %> </td>
        <td> <%= project_card.description %> </td>
        <td> <%= project_card.location %> </td>
        <td> <%= project_card.price %> </td>
        <td><%#= link_to 'Show', project_card %></td>
        <td><%= link_to 'Edit', edit_project_card_path(project_card) %></td>
        <td><%= link_to 'Destroy', project_card, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project card', new_project_card_path %>

<script type="text/javascript">
//    $.ajax({
//        url: "http://localhost:3001/api/biometric/all",
//        method: 'get',
//        dataType: 'json',
//        error: function (request, error) {
//            alert(" Can't do because: " + error)
//        },
//        success: function(response) {
//            alert('here')
//            console.log(response);
//        }
//    })
//    $.ajax({
//        url: 'http://accounts.tangailenterprise.com/api/users/'+ 201 +'/attendances',
//        method: 'POST',
//        dataType: 'json',
//        error: function (request, error) {
//            alert(" Can't do because: " + error)
//        },
//        success: function(response) {
//            alert('here')
//            console.log(response);
//        }
//    })
</script>

app/views/project_cards/new.html.erb
<h1>New Project Card</h1>

<%= render 'form' %>

<%= link_to 'Back', project_cards_path %>

app/views/project_cards/reset_theme.js.erb
$('#project-card').css('background', '#2c2c2c');

app/views/project_cards/set_theme.js.erb
//$('#project-card').css('background-image', 'url(<%= @card.background_image.url %>)');

app/views/project_cards/show.html.erb
<%= raw @project_card.content %>

app/views/project_cards/upload_image.js.erb
alert('ok');

app/views/project_cards/upload_theme.js.erb
$('#project-card').css('background-image', 'url(<%= @card.background_image.url %>)');